cluster: "~/.config/snakemake/{{cookiecutter.profile_name}}/pbs-submit.py --depend \"{dependencies}\""
cluster-status: "~/.config/snakemake/{{cookiecutter.profile_name}}/pbs-status.py"
jobscript: "~/.config/snakemake/{{cookiecutter.profile_name}}/pbs-jobscript.sh"
jobs: 5000
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
max-jobs-per-second: 1
local-cores: 1
rerun-incomplete: true
keep-going: true
